//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllWebApi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Helpers;

    public partial class purchase
    {
        public int pur_id { get; set; }
        public string pur_no { get; set; }
        public System.DateTime date { get; set; }
        public double total_amount { get; set; }
        [NotMapped]
        public List<purchase_product> purchaseProductForList { get; set; }

    }
}
